### ISSUE TITLE
Does not change from `vendor/` to `type:wordpress-plugin` path

### ISSUE THREAD

**Issue by strarsis** [composer/installers#536]
```yml
  "require": {
    "composer/installers": "^2.2",
    "benbodhi/svg-support": "2.5.6",
  },

  "repositories": {
    "wpackagist": {
      "type": "composer",
      "url": "https://wpackagist.org",
      "only": [
        "wpackagist-plugin/*",
        "wpackagist-theme/*"
      ]
    },

    "svg-support-repository": {
      "type": "package",
      "package": {
        "name": "benbodhi/svg-support",
        "type": "wordpress-plugin",
        "version": "2.5.6",
        "source": {
          "url": "https://plugins.svn.wordpress.org/svg-support/",
          "type": "svn",
          "reference": "tags/2.5.6"
        }
      }
    }
  },

  "extra": {
    "installer-paths": {
      "web/app/plugins/{$name}/": [
        "type:wordpress-plugin"
      ]
    }
  },
````

When `"type": "wordpress-plugin"` was missing on a previous `composer update` run, the plugin files end up in `vendor/`.
After `"type": "wordpress-plugin"` was added, and `composer update` ran again, the 
plugin files will be still in `vendor/` and missing in `web/app/plugins/svg-support`.
Only a manual fix/workaround, by removing the directory in `vendor/` and re-running `composer update` 
lets `composer update`; `composer install` put the plugin files into `web/app/plugins/svg-support/` directory.
